AWSTemplateFormatVersion: 2010-09-09
Description: SQS
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MySQS
      SqsManagedSseEnabled: true
      VisibilityTimeout: 100
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 5
  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyDeadLetterSQS
      SqsManagedSseEnabled: true
      VisibilityTimeout: 100
  myPrimaryLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/myPrimaryLambda/app.lambda_handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 900
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          MY_SQS_URL: !GetAtt MyQueue.QueueUrl
      Description: A Lambda function that will send message to sqs
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSQSFullAccess

    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/mySecondLambda/app.lambda_handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 100
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt MyQueue.Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
      Description: A Lambda function that will process the sqs message.
      Policies:
        - AWSLambdaBasicExecutionRole
        # - SQSPollerPolicy:
              # QueueName: !GetAtt MyQueue.QueueName

  myDeadLetterLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/myDeadLetterLambda/app.lambda_handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 100
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt MyDeadLetterQueue.Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
      Description: A Lambda function that will process the dead letter sqs message.
      Policies:
        - AWSLambdaBasicExecutionRole
        # - SQSPollerPolicy:
              # QueueName: !GetAtt MyDeadLetterQueue.QueueName

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"